# Generated by Django 6.1.1 on 2026-09-21 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('claim_type', models.CharField(blank=True, max_length=50)),
                ('authorization_number', models.CharField(blank=True, max_length=50)),
                ('date_of_service', models.DateField()),
                ('total_claim_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('INGESTED', 'Ingested'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('VALIDATION_HOLD', 'Validation Hold'), ('PRICING', 'Pricing'), ('PRICED', 'Priced'), ('PRICING_HOLD', 'Pricing Hold'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PENDED', 'Pended'), ('PENDING_PAYMENT_APPROVAL', 'Pending Payment Approval'), ('PAYMENT_APPROVED', 'Payment Approved'), ('PAYMENT_SCHEDULED', 'Payment Scheduled'), ('PAID', 'Paid'), ('PAYMENT_HOLD', 'Payment Hold')], default='INGESTED', max_length=32)),
                ('hold_reason', models.TextField(blank=True)),
                ('assigned_user', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('membership_effective_date', models.DateField(blank=True, null=True)),
                ('membership_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TERMED', 'Termed')], default='ACTIVE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('npi', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='manual', max_length=50)),
                ('raw_payload', models.JSONField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_logs', to='claims.claim')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='claims.member'),
        ),
        migrations.AddField(
            model_name='claim',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='claims.provider'),
        ),
        migrations.CreateModel(
            name='ServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpt_code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('units', models.PositiveIntegerField(default=1)),
                ('billed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='claims.claim')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='claims.claim')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='claims_clai_status_b4f911_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['member', 'date_of_service'], name='claims_clai_member__63ef2b_idx'),
        ),
    ]
