# Generated by Django 6.1.1 on 2026-09-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('ACH', 'ACH'), ('CHECK', 'Check')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('scheduled_payment_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='SCHEDULED', max_length=10)),
                ('eop_text', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='claims.claim')),
            ],
        ),
    ]
