# Generated by Django 6.0.8 on 2026-09-23 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CLAIMS_SUBMITTER', 'Claims Submitter'), ('CLAIMS_APPROVER', 'Claims Approver'), ('TPA_MANAGER', 'TPA Manager')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claims_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
